'use strict';

/**
 * This file was initially autogenerated by `sequelize-cli`, then modified.
 */

var fs = require('fs');
var path = require('path');
var Sequelize = require('sequelize');
var extend = require('extend-shallow');
var basename = path.basename(module.filename);
var env = process.env.NODE_ENV || 'development';
var db;

module.exports = function(config) {
  if (db) return db;

  config = extend({}, config).db;
  db = {};

  if (config.use_env_variable) {
    var sequelize = new Sequelize(process.env[config.use_env_variable]);
  } else {
    var sequelize = new Sequelize(config.database, config.username, config.password, config);
  }

  fs.readdirSync(__dirname)
    .filter(function(file) {
      return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
    })
    .forEach(function(file) {
      var model = sequelize['import'](path.join(__dirname, file));
      db[model.name] = model;
    });

  Object.keys(db).forEach(function(modelName) {
    if (db[modelName].associate) {
      db[modelName].associate(db);
    }
  });

  db.sequelize = sequelize;
  db.Sequelize = Sequelize;

  if (env === 'production') {
    // add new models for production but don't drop data
    sequelize.sync({force: false});
  } else {
    // replace tables and data for development and test databases
    sequelize.sync({
      force: true,
      match: /_(development|test)$/
    });
  }

  return db;
};

